/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as ExternalLoginRouteImport } from './routes/_external/login'
import { Route as AuthStylistsRouteImport } from './routes/_auth/stylists'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const ExternalLoginRoute = ExternalLoginRouteImport.update({
  id: '/_external/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStylistsRoute = AuthStylistsRouteImport.update({
  id: '/stylists',
  path: '/stylists',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/customers': typeof AuthCustomersRoute
  '/stylists': typeof AuthStylistsRoute
  '/login': typeof ExternalLoginRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/customers': typeof AuthCustomersRoute
  '/stylists': typeof AuthStylistsRoute
  '/login': typeof ExternalLoginRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/stylists': typeof AuthStylistsRoute
  '/_external/login': typeof ExternalLoginRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/customers' | '/stylists' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/customers' | '/stylists' | '/login' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/customers'
    | '/_auth/stylists'
    | '/_external/login'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ExternalLoginRoute: typeof ExternalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_external/login': {
      id: '/_external/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ExternalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/stylists': {
      id: '/_auth/stylists'
      path: '/stylists'
      fullPath: '/stylists'
      preLoaderRoute: typeof AuthStylistsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthStylistsRoute: typeof AuthStylistsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCustomersRoute: AuthCustomersRoute,
  AuthStylistsRoute: AuthStylistsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ExternalLoginRoute: ExternalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
